### ISSUE TITLE
tmp directory creation

### ISSUE THREAD

**Issue by diegoamc** [mezuro/packaging#12]
Fix the path for the tmp directory. Currently, it will be created on `/usr/share...` but it should be created at `/var/lib...`.

See the [post_install](https://github.com/mezuro/packaging/blob/master/scripts/post_install.sh#L59) script for more details.

**Comment by diegoamc** [comment]
Installing the package on a brand new CentOS machine, the `tmp` directory is not owned by `kalibro_processor` but is owned by `root` instead.

It seems c6869db0d93fbabd5aabce12e71ddd3ef1c8679d did not make effect. Can anyone else test it? @danielkza, @marcheing, @dread-uo. Maybe I'm missing something.

**Comment by rafamanzo** [comment]
Closed via https://github.com/mezuro/packaging/pull/14
